# permissions for end users to edit alertpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: newrelic-kubernetes-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: alertpolicy-editor-role
rules:
- apiGroups:
  - alerts.k8s.newrelic.com
  resources:
  - alertpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alerts.k8s.newrelic.com
  resources:
  - alertpolicies/status
  verbs:
  - get
