apiVersion: alerts.k8s.newrelic.com/v1
kind: AlertPolicy
metadata:
  labels:
    app.kubernetes.io/name: newrelic-kubernetes-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: alertpolicy-sample
spec:
  # TODO(user): Add fields here
  apiKey: <your New Relic User key>
  region: "US" # EU or US
  name: ExampleK8Policy # Policy Name
  incidentPreference: PER_POLICY # PER_POLICY, PER_CONDITION, PER_CONDITION_AND_TARGET
