apiVersion: alerts.k8s.newrelic.com/v1
kind: AlertWorkflow
metadata:
  labels:
    app.kubernetes.io/name: newrelic-kubernetes-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: alertworkflow-sample
spec:
  # TODO(user): Add fields here
