apiVersion: alerts.k8s.newrelic.com/v1
kind: NrqlCondition
metadata:
  labels:
    app.kubernetes.io/name: newrelic-kubernetes-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: nrqlcondition-sample
spec:
  accountId: <your New Relic account ID>
  apiKey: <your New Relic User key>
  # api_key_secret:
  #   name: nr-api-key
  #   namespace: default
  #   key_name: api-key
  region: "US"
  name: "Example NRQL Condition"
  description: "test description"
  # Must reference an existing New Relic alert policy from your account
  existingPolicyId: "333"
  type: STATIC # STATIC | BASELINE
  nrql:
    query: "SELECT count(*) FROM Transaction"
  enabled: true
  runbookUrl: "https://www.google.com"
  terms:
    - threshold: "85"
      thresholdOccurrences: ALL
      thresholdDuration: 60
      priority: CRITICAL
      operator: ABOVE
  expiration:
    expirationDuration: 360
    closeViolationsOnExpiration: true
    openViolationOnExpiration: false
  signal:
    aggregationWindow: 60
    evaluationDelay: 5
    fillOption: NONE
    aggregationMethod: EVENT_FLOW
    aggregationDelay: 60
