apiVersion: alerts.k8s.newrelic.com/v1
kind: AlertDestination
metadata:
  labels:
    app.kubernetes.io/name: newrelic-kubernetes-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: alertdestination-pd-example
spec:
  accountId: 1
  apiKey: <api_key>
  region: "US"
  name: "test-pd-destination"
  properties:
    - key: ""
      value: ""
  auth:
    type: "TOKEN"
    token:
      prefix: "Bearer"
      token: "<token>"
  type: "PAGERDUTY_SERVICE_INTEGRATION"
  active: true
