apiVersion: alerts.k8s.newrelic.com/v1
kind: AlertDestination
metadata:
  labels:
    app.kubernetes.io/name: newrelic-kubernetes-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: alertdestination-mobilepush-example
spec:
  accountId: 1
  apiKey: <api_key>
  region: "US"
  name: "test-mobilepush-destination"
  properties:
    - key: "userId"
      value: "11111" #must be a valid userId
  type: "MOBILE_PUSH"
  active: false
