apiVersion: alerts.k8s.newrelic.com/v1
kind: AlertDestination
metadata:
  labels:
    app.kubernetes.io/name: newrelic-kubernetes-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: alertdestination-email-example
spec:
  accountId: 1
  apiKey: <api_key>
  region: "US"
  name: "test-email-destination"
  properties:
    - displayValue: "testemail@test.com"
      key: "email"
      value: "testemail@test.com"
  type: "EMAIL"
  active: true
